import { tool } from "@langchain/core/tools";
import { z } from "zod";

import { createAgent } from "langchain";
import { librarianAgentModel } from "@/lib/llm/agentModels";
import { fetchDocumentListTool } from "@/lib/tools/fetchDocumentList";
import { LIBRARIAN_SYSTEM_PROMPT } from "../../prompts/librarianSystemPrompt";
import { writeFileTool } from "@/lib/tools/fileSystemTools";
import { toolMonitoringMiddleware } from "../../middleware/toolMonitoringMiddleWare";






const  agent= createAgent({
    model: librarianAgentModel,
  systemPrompt:LIBRARIAN_SYSTEM_PROMPT,
  tools: [fetchDocumentListTool, writeFileTool],
   middleware:[toolMonitoringMiddleware],
});

export const LibrarianAgent = tool(
  async ({ query ,userId,projectId}) => {
    const result = await agent.invoke({
      messages: [{ role: "user", content: query+` Use the userId:${userId} and projectId:${projectId}
        to fetch data in external system` }]
    });
    return result.messages.at(-1)?.text ?? "";
  },
  {
    name: "LibrarianAgent",
    description: `
LibrarianAgent is responsible for identifying and returning the most relevant documents
based on a set of semantic queries provided by the ManagerAgent. 

It performs the following tasks:
1. Receives semantic queries (generated by MultiQueryAgent) from the manager.
2. Fetches the complete document list using its tools (e.g., fetchDocumentList).
3. Compares the queries against each document's metadata and content.
4. Constructs a structured array of concerned documents with matching queries:
   [
     {
       title: "",
       description: "",
       projectId: "",
       userId: "",
       queries: ["query1", "query2", ...]
     }
   ]
5. Returns only the concerned documents to ManagerAgent for further processing.

    `,
    schema: z.object({
      query: z.string().describe("Set of semantic queries from ManagerAgent to identify relevant documents"),
      userId:z.string().describe('userId to fetch data in external system'),
      projectId:z.string().describe('projectId to fetch data in external system')

    }),
  }
);
