// import type { Metadata } from "next";

"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { store } from "@/store";

import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "next-themes";
import { Agentation } from "agentation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: Session | null;
}>) {
  return (
    <html suppressHydrationWarning>
      <head></head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SessionProvider session={session}>
            <Provider store={store}>
              {children}
              <ToastContainer />
              {process.env.NODE_ENV === "development" && <Agentation />}
            </Provider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
